#name: CI
#on: [push]
#jobs:
  #build:
    #runs-on: ubuntu-latest
    #steps:
    #- uses: actions/checkout@v2
    #- name: Setup upterm session
      #uses: lhotari/action-upterm@v1
name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo snap install microstack --devmode --beta
      - run: sudo microstack init --auto --control
      - run: curl https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img -o focal.img
      - run: microstack.openstack image create --file focal.img ubuntu-20.04-focal-x86_64
      - run: ssh-keygen -t rsa -q -f "$HOME/.ssh/id_rsa" -N ""
      - run: terraform init
      - run: eval $(ssh-agent) && ssh-add && source /var/snap/microstack/common/etc/microstack.rc && terraform apply -auto-approve
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1

