name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo snap install microstack --beta
      - run: sudo microstack init --auto --control
      - run: microstack.openstack keypair list
      - run: microstack.openstack image list
      - run: microstack.openstack flavor list
      - run: microstack launch cirros -n test
      - run: sudo snap get microstack config.credentials.keystone-password

